### ISSUE TITLE
Improve User Experience

### ISSUE THREAD

**Issue by raeldc** [nooku/nooku-support#14]
Right now, the user experience is very basic. It's based to much on com:todo. 

So it's time to make it work like a real support component. Here are some quick suggestions:

* On ticket READ, it shouldn't always show the edit view. It should have an "Edit" button for ticket owner or admin. 
* Don't use the "Save and Close" toolbar button because it's confusing, it doesn't really close the ticket but it closes the edit view.
* Add a quick button to mark the ticket as closed. 
* When displaying status on the Edit view, don't show "All", that's only for filtering.

An idea for the future:

* Show activities within the ticket alongside comments. It's much like how Tickets in GitHub work.

**Comment by johanjanssens** [comment]
@raeldc Good suggestions. Instead of putting the suggestions into an issue we might be better doing them in the wiki ? We can then discuss them a bit and pick the most interesting ones ?

**Comment by raeldc** [comment]
@johanjanssens Added them here https://github.com/nooku/nooku-support/wiki/Planned-Features

**Comment by johanjanssens** [comment]
@raeldc lets do it like that in the future. Closing this as invalid.
