### ISSUE TITLE
Use CKEditor

### ISSUE THREAD

**Issue by jebbdomingo** [nooku/nooku-support#3]

**Comment by raeldc** [comment]
@jebbdomingo, better force the Comments to use the "basic" template of ckeditor. Take note that nooku-comments should use that template by default. 

We only want basic editing here and not rich text editing.

**Comment by jebbdomingo** [comment]
Note: please use the branch of nooku-ckeditor https://github.com/nooku/nooku-ckeditor/tree/feature/6-phpconfigurable for testing

**Comment by jebbdomingo** [comment]
If the solution is acceptable, could we implement it in the framework itself?

**Comment by jebbdomingo** [comment]
Related Pull Request has been merged and closed
