### ISSUE TITLE
Comply to standard directory structure

### ISSUE THREAD

**Issue by jebbdomingo** [nooku/nooku-support#4]
Re-structure source codes into "code" directory

**Comment by johanjanssens** [comment]
@jebbdomingo if you are building this as a re-usable component all the code would go directly in the root folder. Example : https://github.com/nooku/nooku-activities If you are building this as a Joomla component, then the structure would follow : https://github.com/joomlatools/joomlatools-todo

@raeldc  @tomjanssens : Is the goal here to build a complete re-usable base component or are we doing this as a Joomla only component ?

**Comment by raeldc** [comment]
@johanjanssens, the direction that we were taking is to make it work as a Joomla component first, then when it's working, we could refactor it into a completely reusable non-Joomla component and create a separate repo for the Joomla Extension version. We are trying to make it work inside the Joomla Platform for now, thus the Joomla Component folder structure.

**Comment by johanjanssens** [comment]
@raeldc Agreed, had a talk with @jebbdomingo on that too. So then this does indeed need to be refactored to follow the dir structure that complies with the symlinker. Additionaly I would move the repo to joomlatools and not keep it here as we are not building a re-usable component, merely a Joomla component.

**Comment by johanjanssens** [comment]
@raeldc @jebbdomingo As discussed component can indeed be refactored to use the standard directory structure. Once this is completed, let me know and I will move the repo to Joomlatools org where it belongs.

**Comment by jebbdomingo** [comment]
@johanjanssens yes I will do it
